name: Multi Event Sample Workflow

on:
  workflow_dispatch:

  schedule:
    - cron: "0 5 * * *"

  push:
    branches:
      - "**"

jobs:
  sample_job:
    runs-on: ubuntu-latest
    steps:
      - name: Show event
        run: echo "Triggered by ${{ github.event_name }}"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Done
        run: echo "Workflow completed successfully."
